# 行列演算の基礎

In [58]:
import numpy as np

In [4]:
#ベクトルの定義
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [5]:
#行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [7]:
#転置
Xt = X.T
Xt

array([[1, 3],
       [2, 4]])

In [9]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
#行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# Numpyでよく使う処理

In [15]:
X = np.array([
    [2,3,4],
    [1,2,3]    
])

In [16]:
print(X)

[[2 3 4]
 [1 2 3]]


In [17]:
X.shape

(2, 3)

In [18]:
row,col = X.shape

In [19]:
row

2

In [20]:
col

3

In [21]:
for x in X:
    print(x)
    print("---")

[2 3 4]
---
[1 2 3]
---


# 演習問題

In [22]:
#データの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [23]:
#yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8],
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [25]:
#Step1 行列積：dot
XtX = np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [27]:
# Step2 
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [28]:
#Step3
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [30]:
#Step4
w = np.dot(XtX_inv,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [2]:
import sklearn

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
#モデルの宣言
model = LinearRegression()

In [34]:
#モデルの学習　←　パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [35]:
#　調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [36]:
model.intercept_

array([-0.14285714])

In [37]:
#　予測精度　←　決定係数
model.score(X,y)

0.6923076923076923

In [38]:
#　予測値の計算
x = np.array([
    [1,2,3]
])

In [40]:
y_pred = model.predict(x)
y_pred

array([[3.]])

# 実データでの演習

In [3]:
# データの読み込み
import pandas as pd

In [4]:
# CSVファイルの読み込み
df = pd.read_csv('housing.csv')

In [5]:
df.head()

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222  18.7  394.63   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222  18.7  396.90   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7  
3  2.94  33.4  
4  5.33  36.2

In [6]:
# レコード数の確認（サンプル数）
len(df)

506

In [7]:
#統計量の算出
df.describe()

x1          x2          x3          x4          x5          x6  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

               x7          x8          x9         x10         x11         x12  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

              x13           y  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

# 分布の確認

In [2]:
!pip3 install seaborn

You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [1]:
!pip3 uninstall seaborn

Skipping seaborny as it is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [1]:
%matplotlib inline
import seaborn 

ModuleNotFoundError: No module named 'seaborn'

In [5]:
import pandas 

# 相関関係の確認

In [5]:
#　相関係数の算出
df.corr()

x1        x2        x3        x4        x5        x6        x7  \
x1   1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
x2  -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
x3   0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
x4  -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
x5   0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
x6  -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
x7   0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
x8  -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
x9   0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
x10  0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
x11  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
x12 -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
x13  0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
y   -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

           x8        x9       x10       x11       x12       x13         y  
x1  -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
x2   0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
x3  -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
x4  -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
x5  -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
x6   0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
x7  -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
x8   1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
x9  -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
x10 -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
x11 -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
x12  0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
x13 -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
y    0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [9]:
# 相関係数を目視で確認
sns.pairplot(df)

NameError: name 'sns' is not defined

In [10]:
!pip3 list

Package            Version
------------------ -------
appnope            0.1.0  
backcall           0.1.0  
bleach             3.0.2  
cycler             0.10.0 
decorator          4.3.0  
defusedxml         0.5.0  
entrypoints        0.3    
ipykernel          5.1.0  
ipython            7.2.0  
ipython-genutils   0.2.0  
ipywidgets         7.4.2  
jedi               0.13.2 
Jinja2             2.10   
jsonschema         2.6.0  
jupyter            1.0.0  
jupyter-client     5.2.4  
jupyter-console    6.0.0  
jupyter-core       4.4.0  
kiwisolver         1.0.1  
MarkupSafe         1.1.0  
matplotlib         3.0.2  
mistune            0.8.4  
nbconvert          5.4.0  
nbformat           4.4.0  
notebook           5.7.4  
numpy              1.15.4 
pandas             0.23.4 
pandocfilters      1.4.2  
parso              0.3.1  
pexpect            4.6.0  
pickleshare        0.7.5  
pip                10.0.1 
prometheus-client  0.5.0  
prompt-toolkit     2.0.7  
ptyprocess         0.6.0  
P

In [12]:
import seaborn

ModuleNotFoundError: No module named 'seaborn'

In [6]:
df.head(3)

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7

In [7]:
#df,iloc[行,列]

In [8]:
df.iloc[0,0]

0.00632

In [18]:
X = df.iloc[:, :-1]

In [19]:
X

x1    x2     x3  x4     x5     x6     x7      x8  x9  x10   x11  \
0     0.00632  18.0   2.31   0  0.538  6.575   65.2  4.0900   1  296  15.3   
1     0.02731   0.0   7.07   0  0.469  6.421   78.9  4.9671   2  242  17.8   
2     0.02729   0.0   7.07   0  0.469  7.185   61.1  4.9671   2  242  17.8   
3     0.03237   0.0   2.18   0  0.458  6.998   45.8  6.0622   3  222  18.7   
4     0.06905   0.0   2.18   0  0.458  7.147   54.2  6.0622   3  222  18.7   
5     0.02985   0.0   2.18   0  0.458  6.430   58.7  6.0622   3  222  18.7   
6     0.08829  12.5   7.87   0  0.524  6.012   66.6  5.5605   5  311  15.2   
7     0.14455  12.5   7.87   0  0.524  6.172   96.1  5.9505   5  311  15.2   
8     0.21124  12.5   7.87   0  0.524  5.631  100.0  6.0821   5  311  15.2   
9     0.17004  12.5   7.87   0  0.524  6.004   85.9  6.5921   5  311  15.2   
10    0.22489  12.5   7.87   0  0.524  6.377   94.3  6.3467   5  311  15.2   
11    0.11747  12.5   7.87   0  0.524  6.009   82.9  6.2267   5  311  15.2   
12    0.09378  12.5   7.87   0  0.524  5.889   39.0  5.4509   5  311  15.2   
13    0.62976   0.0   8.14   0  0.538  5.949   61.8  4.7075   4  307  21.0   
14    0.63796   0.0   8.14   0  0.538  6.096   84.5  4.4619   4  307  21.0   
15    0.62739   0.0   8.14   0  0.538  5.834   56.5  4.4986   4  307  21.0   
16    1.05393   0.0   8.14   0  0.538  5.935   29.3  4.4986   4  307  21.0   
17    0.78420   0.0   8.14   0  0.538  5.990   81.7  4.2579   4  307  21.0   
18    0.80271   0.0   8.14   0  0.538  5.456   36.6  3.7965   4  307  21.0   
19    0.72580   0.0   8.14   0  0.538  5.727   69.5  3.7965   4  307  21.0   
20    1.25179   0.0   8.14   0  0.538  5.570   98.1  3.7979   4  307  21.0   
21    0.85204   0.0   8.14   0  0.538  5.965   89.2  4.0123   4  307  21.0   
22    1.23247   0.0   8.14   0  0.538  6.142   91.7  3.9769   4  307  21.0   
23    0.98843   0.0   8.14   0  0.538  5.813  100.0  4.0952   4  307  21.0   
24    0.75026   0.0   8.14   0  0.538  5.924   94.1  4.3996   4  307  21.0   
25    0.84054   0.0   8.14   0  0.538  5.599   85.7  4.4546   4  307  21.0   
26    0.67191   0.0   8.14   0  0.538  5.813   90.3  4.6820   4  307  21.0   
27    0.95577   0.0   8.14   0  0.538  6.047   88.8  4.4534   4  307  21.0   
28    0.77299   0.0   8.14   0  0.538  6.495   94.4  4.4547   4  307  21.0   
29    1.00245   0.0   8.14   0  0.538  6.674   87.3  4.2390   4  307  21.0   
..        ...   ...    ...  ..    ...    ...    ...     ...  ..  ...   ...   
476   4.87141   0.0  18.10   0  0.614  6.484   93.6  2.3053  24  666  20.2   
477  15.02340   0.0  18.10   0  0.614  5.304   97.3  2.1007  24  666  20.2   
478  10.23300   0.0  18.10   0  0.614  6.185   96.7  2.1705  24  666  20.2   
479  14.33370   0.0  18.10   0  0.614  6.229   88.0  1.9512  24  666  20.2   
480   5.82401   0.0  18.10   0  0.532  6.242   64.7  3.4242  24  666  20.2   
481   5.70818   0.0  18.10   0  0.532  6.750   74.9  3.3317  24  666  20.2   
482   5.73116   0.0  18.10   0  0.532  7.061   77.0  3.4106  24  666  20.2   
483   2.81838   0.0  18.10   0  0.532  5.762   40.3  4.0983  24  666  20.2   
484   2.37857   0.0  18.10   0  0.583  5.871   41.9  3.7240  24  666  20.2   
485   3.67367   0.0  18.10   0  0.583  6.312   51.9  3.9917  24  666  20.2   
486   5.69175   0.0  18.10   0  0.583  6.114   79.8  3.5459  24  666  20.2   
487   4.83567   0.0  18.10   0  0.583  5.905   53.2  3.1523  24  666  20.2   
488   0.15086   0.0  27.74   0  0.609  5.454   92.7  1.8209   4  711  20.1   
489   0.18337   0.0  27.74   0  0.609  5.414   98.3  1.7554   4  711  20.1   
490   0.20746   0.0  27.74   0  0.609  5.093   98.0  1.8226   4  711  20.1   
491   0.10574   0.0  27.74   0  0.609  5.983   98.8  1.8681   4  711  20.1   
492   0.11132   0.0  27.74   0  0.609  5.983   83.5  2.1099   4  711  20.1   
493   0.17331   0.0   9.69   0  0.585  5.707   54.0  2.3817   6  391  19.2   
494   0.27957   0.0   9.69   0  0.585  5.926   42.6  2.3817   6  391  19.2   
495   0.17899   0.0   9.69   0  0

In [26]:
y = df.iloc[:, -1]

In [27]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
5      28.7
6      22.9
7      27.1
8      16.5
9      18.9
10     15.0
11     18.9
12     21.7
13     20.4
14     18.2
15     19.9
16     23.1
17     17.5
18     20.2
19     18.2
20     13.6
21     19.6
22     15.2
23     14.5
24     15.6
25     13.9
26     16.6
27     14.8
28     18.4
29     21.0
       ... 
476    16.7
477    12.0
478    14.6
479    21.4
480    23.0
481    23.7
482    25.0
483    21.8
484    20.6
485    21.2
486    19.1
487    20.6
488    15.2
489     7.0
490     8.1
491    13.6
492    20.1
493    21.8
494    24.5
495    23.1
496    19.7
497    18.3
498    21.2
499    17.5
500    16.8
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: y, Length: 506, dtype: float64

## モデルの構築と検証

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
#モデルの宣言
model = LinearRegression()

In [30]:
#モデルの学習
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [32]:
#検証（決定係数の計算）
model.score(X,y)

0.7406426641094094

## 訓練データと検証データ

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
#訓練データと検証データの分割
X_train,X_test,y_train, y_test = train_test_split(X,y, test_size=0.4, random_state = 1) #random_stateは乱数のシードを固定

In [39]:
X_train.head()

x1   x2     x3  x4     x5     x6    x7      x8  x9  x10   x11  \
452  5.09017  0.0  18.10   0  0.713  6.297  91.8  2.3682  24  666  20.2   
346  0.06162  0.0   4.39   0  0.442  5.898  52.3  8.0136   3  352  18.8   
295  0.12932  0.0  13.92   0  0.437  6.678  31.1  5.9604   4  289  16.0   
88   0.05660  0.0   3.41   0  0.489  7.007  86.3  3.4217   2  270  17.8   
322  0.35114  0.0   7.38   0  0.493  6.041  49.9  4.7211   5  287  19.6   

        x12    x13  
452  385.09  17.27  
346  364.61  12.67  
295  396.90   6.27  
88   396.90   5.50  
322  396.90   7.70

In [38]:
y_train.head()

452    16.1
346    17.2
295    28.6
88     23.6
322    20.4
Name: y, dtype: float64

In [40]:
# モデルの学習
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [41]:
#検証　←　検証データ
model.score(X_test,y_test)

0.7209056672661757

In [42]:
#検証　⇦　訓練データ
model.score(X_train,y_train)

0.7468316520140627

## 予測値の計算

In [43]:
x = X.iloc[0, :]
x

x1       0.00632
x2      18.00000
x3       2.31000
x4       0.00000
x5       0.53800
x6       6.57500
x7      65.20000
x8       4.09000
x9       1.00000
x10    296.00000
x11     15.30000
x12    396.90000
x13      4.98000
Name: 0, dtype: float64

In [45]:
#予測値の計算
y_pred = model.predict([x])
y_pred

array([29.42368847])

## モデルの保存

In [46]:
from sklearn.externals import joblib

In [47]:
#モデルの保存
joblib.dump(model, 'model.pkl')

['model.pkl']

# モデルの読み込み

In [48]:
model_new = joblib.load('model.pkl')

In [49]:
x

x1       0.00632
x2      18.00000
x3       2.31000
x4       0.00000
x5       0.53800
x6       6.57500
x7      65.20000
x8       4.09000
x9       1.00000
x10    296.00000
x11     15.30000
x12    396.90000
x13      4.98000
Name: 0, dtype: float64

In [50]:
model_new.predict([x])

array([29.42368847])

## パラメータの確認

In [52]:
#パラメータwの値
model.coef_

array([-8.95714048e-02,  6.73132853e-02,  5.04649248e-02,  2.18579583e+00,
       -1.72053975e+01,  3.63606995e+00,  2.05579939e-03, -1.36602886e+00,
        2.89576718e-01, -1.22700072e-02, -8.34881849e-01,  9.40360790e-03,
       -5.04008320e-01])

In [55]:
np.set_printoptions(precision=3,suppress=True) #指数関数の表示が禁止

In [56]:
model.coef_

array([ -0.09 ,   0.067,   0.05 ,   2.186, -17.205,   3.636,   0.002,
        -1.366,   0.29 ,  -0.012,  -0.835,   0.009,  -0.504])

In [57]:
df.head(3)

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7

重み(パラメータw)を見るだけでは、どの変数が影響を与えているかわからない

## データの読み込み

In [59]:
#CSVデータの読み込み
df.head(3)

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7

# 分布の確認

# 外れ値除去( 3σ法 )

In [60]:
col = 'x6'

In [61]:
mean = df.mean()
mean

x1       3.613524
x2      11.363636
x3      11.136779
x4       0.069170
x5       0.554695
x6       6.284634
x7      68.574901
x8       3.795043
x9       9.549407
x10    408.237154
x11     18.455534
x12    356.674032
x13     12.653063
y       22.532806
dtype: float64

In [62]:
mean[col]

6.284634387351788

In [63]:
# 標準偏差（standard deviation)
sigma = df.std()
sigma

x1       8.601545
x2      23.322453
x3       6.860353
x4       0.253994
x5       0.115878
x6       0.702617
x7      28.148861
x8       2.105710
x9       8.707259
x10    168.537116
x11      2.164946
x12     91.294864
x13      7.141062
y        9.197104
dtype: float64

In [64]:
sigma[col]

0.7026171434153234

In [65]:
low = mean[col] - 3 * sigma[col]
low

4.176782957105817

In [66]:
high = mean[col] + 3 * sigma[col]
high

8.392485817597759

In [71]:
df2 = df[(df[col] > low) & (df[col] < high)]
df2

x1    x2     x3  x4     x5     x6     x7      x8  x9  x10   x11  \
0     0.00632  18.0   2.31   0  0.538  6.575   65.2  4.0900   1  296  15.3   
1     0.02731   0.0   7.07   0  0.469  6.421   78.9  4.9671   2  242  17.8   
2     0.02729   0.0   7.07   0  0.469  7.185   61.1  4.9671   2  242  17.8   
3     0.03237   0.0   2.18   0  0.458  6.998   45.8  6.0622   3  222  18.7   
4     0.06905   0.0   2.18   0  0.458  7.147   54.2  6.0622   3  222  18.7   
5     0.02985   0.0   2.18   0  0.458  6.430   58.7  6.0622   3  222  18.7   
6     0.08829  12.5   7.87   0  0.524  6.012   66.6  5.5605   5  311  15.2   
7     0.14455  12.5   7.87   0  0.524  6.172   96.1  5.9505   5  311  15.2   
8     0.21124  12.5   7.87   0  0.524  5.631  100.0  6.0821   5  311  15.2   
9     0.17004  12.5   7.87   0  0.524  6.004   85.9  6.5921   5  311  15.2   
10    0.22489  12.5   7.87   0  0.524  6.377   94.3  6.3467   5  311  15.2   
11    0.11747  12.5   7.87   0  0.524  6.009   82.9  6.2267   5  311  15.2   
12    0.09378  12.5   7.87   0  0.524  5.889   39.0  5.4509   5  311  15.2   
13    0.62976   0.0   8.14   0  0.538  5.949   61.8  4.7075   4  307  21.0   
14    0.63796   0.0   8.14   0  0.538  6.096   84.5  4.4619   4  307  21.0   
15    0.62739   0.0   8.14   0  0.538  5.834   56.5  4.4986   4  307  21.0   
16    1.05393   0.0   8.14   0  0.538  5.935   29.3  4.4986   4  307  21.0   
17    0.78420   0.0   8.14   0  0.538  5.990   81.7  4.2579   4  307  21.0   
18    0.80271   0.0   8.14   0  0.538  5.456   36.6  3.7965   4  307  21.0   
19    0.72580   0.0   8.14   0  0.538  5.727   69.5  3.7965   4  307  21.0   
20    1.25179   0.0   8.14   0  0.538  5.570   98.1  3.7979   4  307  21.0   
21    0.85204   0.0   8.14   0  0.538  5.965   89.2  4.0123   4  307  21.0   
22    1.23247   0.0   8.14   0  0.538  6.142   91.7  3.9769   4  307  21.0   
23    0.98843   0.0   8.14   0  0.538  5.813  100.0  4.0952   4  307  21.0   
24    0.75026   0.0   8.14   0  0.538  5.924   94.1  4.3996   4  307  21.0   
25    0.84054   0.0   8.14   0  0.538  5.599   85.7  4.4546   4  307  21.0   
26    0.67191   0.0   8.14   0  0.538  5.813   90.3  4.6820   4  307  21.0   
27    0.95577   0.0   8.14   0  0.538  6.047   88.8  4.4534   4  307  21.0   
28    0.77299   0.0   8.14   0  0.538  6.495   94.4  4.4547   4  307  21.0   
29    1.00245   0.0   8.14   0  0.538  6.674   87.3  4.2390   4  307  21.0   
..        ...   ...    ...  ..    ...    ...    ...     ...  ..  ...   ...   
476   4.87141   0.0  18.10   0  0.614  6.484   93.6  2.3053  24  666  20.2   
477  15.02340   0.0  18.10   0  0.614  5.304   97.3  2.1007  24  666  20.2   
478  10.23300   0.0  18.10   0  0.614  6.185   96.7  2.1705  24  666  20.2   
479  14.33370   0.0  18.10   0  0.614  6.229   88.0  1.9512  24  666  20.2   
480   5.82401   0.0  18.10   0  0.532  6.242   64.7  3.4242  24  666  20.2   
481   5.70818   0.0  18.10   0  0.532  6.750   74.9  3.3317  24  666  20.2   
482   5.73116   0.0  18.10   0  0.532  7.061   77.0  3.4106  24  666  20.2   
483   2.81838   0.0  18.10   0  0.532  5.762   40.3  4.0983  24  666  20.2   
484   2.37857   0.0  18.10   0  0.583  5.871   41.9  3.7240  24  666  20.2   
485   3.67367   0.0  18.10   0  0.583  6.312   51.9  3.9917  24  666  20.2   
486   5.69175   0.0  18.10   0  0.583  6.114   79.8  3.5459  24  666  20.2   
487   4.83567   0.0  18.10   0  0.583  5.905   53.2  3.1523  24  666  20.2   
488   0.15086   0.0  27.74   0  0.609  5.454   92.7  1.8209   4  711  20.1   
489   0.18337   0.0  27.74   0  0.609  5.414   98.3  1.7554   4  711  20.1   
490   0.20746   0.0  27.74   0  0.609  5.093   98.0  1.8226   4  711  20.1   
491   0.10574   0.0  27.74   0  0.609  5.983   98.8  1.8681   4  711  20.1   
492   0.11132   0.0  27.74   0  0.609  5.983   83.5  2.1099   4  711  20.1   
493   0.17331   0.0   9.69   0  0.585  5.707   54.0  2.3817   6  391  19.2   
494   0.27957   0.0   9.69   0  0.585  5.926   42.6  2.3817   6  391  19.2   
495   0.17899   0.0   9.69   0  0

In [73]:
len(df)

506

In [74]:
len(df2)

498

In [75]:
# 分布の確認

In [76]:
cols = df.columns

In [77]:
cols

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11',
       'x12', 'x13', 'y'],
      dtype='object')

In [78]:
_df = df
for col in cols:
    #3σ法の上限値を設定
    low = mean[col] -3 * sigma[col]
    high = mean[col] + 3 * sigma[col]
    #条件で絞り込み
    _df = _df[(_df[col] > low)&(_df[col]< high)] 

In [79]:
#オリジナル
len(df)

506

In [80]:
#3a法適用後
len(_df)

415

サンプルが減る場合の対処法
-  外れ値は取り除く
- 外れ値を平均もしくは中央値で埋める
- 主成分分析等を使って、潜在変数に変換した後に3σ法を適用　⇦　高度

## 入力変数と出力変数に分割

In [82]:
_df.head(3)

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7

In [85]:
X = _df.iloc[:,:-1]
y = _df.iloc[:, -1]

## 訓練データと検証データに分割

In [90]:
X_train,X_test,y_train,y_text = train_test_split(X,y, test_size=0.4,random_state =1)

## 重回帰分析

In [91]:
#モデルを宣言
model = LinearRegression()

In [92]:
#モデルの学習
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [93]:
#検証　⇦　訓練データ
model.score(X_train,y_train)

0.7972109224535133

In [95]:
#　検証　⇦　検証データ
model.score(X_test,y_test)

ValueError: Found input variables with inconsistent numbers of samples: [203, 166]

## スケーリング

In [96]:
from sklearn.preprocessing import StandardScaler

In [97]:
#scalerの宣言
scaler = StandardScaler()

In [99]:
# scalerの学習　⇦　平均と標準偏差を計算
scaler.fit(X_train)

/Users/nakanoyuuto/Library/Mobile Documents/com~apple~CloudDocs/Documents/WE/Competition-Team/practice_ML/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [100]:
# scaling
X_train2 = scaler.transform(X_train)
X_test2 = scaler.transform(X_test)

/Users/nakanoyuuto/Library/Mobile Documents/com~apple~CloudDocs/Documents/WE/Competition-Team/practice_ML/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  
/Users/nakanoyuuto/Library/Mobile Documents/com~apple~CloudDocs/Documents/WE/Competition-Team/practice_ML/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


In [101]:
X_train2

array([[-0.45 , -0.471, -0.015, ...,  0.372,  0.067, -0.734],
       [-0.454, -0.471, -0.739, ...,  0.372,  0.381, -0.328],
       [-0.2  , -0.471,  1.295, ..., -1.755, -0.182, -0.757],
       ...,
       [ 0.494, -0.471,  1.074, ...,  0.844,  0.28 , -0.121],
       [-0.457,  0.61 , -0.589, ...,  0.088,  0.448, -0.883],
       [-0.473, -0.471, -0.739, ...,  0.372,  0.448, -0.541]])

In [102]:
# モデルの宣言
model = LinearRegression()

In [103]:
model.fit(X_train2,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [104]:
#検証　⇦　訓練データ
model.score(X_train2,y_train)

0.7972109224535133

In [105]:
model.score(X_test2,y_test)

ValueError: Found input variables with inconsistent numbers of samples: [203, 166]

In [106]:
#重みの確認
model.coef_

array([-0.195,  0.212,  0.508,  0.   , -1.213,  3.92 , -0.37 , -1.857,
        1.166, -1.529, -1.873,  0.244, -2.761])